// Retrieval engine for the KDC-RAG Vercel deployment.
//
// Data file strategy:
//   - chunks.json   → ES module import. Webpack inlines JSON into the function
//                     bundle natively, so chunk text isn't publicly accessible.
//   - embeddings.bin → static asset under web/public/, fetched once on cold
//                      start. ~24 MB; sub-second on the same Vercel region.
//                      Cached in module memory for the function's lifetime.
//
// `ensureLoaded` is async because of the embedding fetch. To keep the rest of
// the codebase mostly synchronous, all consumers should `await ensureLoaded()`
// before calling `retrieve` / `getCorpusStats` / `getChunkText`. Concurrent
// callers share a single in-flight load promise so cold starts don't double-
// fetch.

import { buildBM25, tokenize, type BM25Index } from "./bm25";
import {
  EMBEDDING_DIM,
  RERANK_CANDIDATES,
  RRF_K,
  TOP_K,
} from "./constants";
import type { Chunk, DocType, SourceRef } from "./types";

// JSON: webpack inlines this as an object literal at build time. The chunk
// text body is included in the function bundle, NOT served from public/.
import chunksData from "../data/chunks.json";

let _chunks: Chunk[] | null = null;
let _embeddings: Float32Array | null = null; // (N, EMBEDDING_DIM) row-major
let _bm25: BM25Index | null = null;
let _loadPromise: Promise<void> | null = null;

function deploymentBaseUrl(): string {
  // Vercel populates VERCEL_URL with the host (no protocol).
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  // Custom override for local dev or self-hosted setups.
  if (process.env.NEXT_PUBLIC_SITE_URL) return process.env.NEXT_PUBLIC_SITE_URL;
  // `next dev` default.
  return "http://localhost:3000";
}

async function fetchEmbeddings(): Promise<Float32Array> {
  const url = `${deploymentBaseUrl()}/embeddings.bin`;

  // Vercel's Deployment Protection blocks anonymous HTTP requests to preview
  // (and optionally production) deployments — even from other functions on
  // the same deployment. If the project has "Protection Bypass for
  // Automation" enabled, Vercel exposes the secret as
  // VERCEL_AUTOMATION_BYPASS_SECRET; we attach it via the documented header
  // so the self-fetch is allowed through.
  const headers: Record<string, string> = {};
  const bypass = process.env.VERCEL_AUTOMATION_BYPASS_SECRET;
  if (bypass) headers["x-vercel-protection-bypass"] = bypass;

  const res = await fetch(url, { cache: "force-cache", headers });

  if (res.status === 401 || res.status === 403) {
    throw new Error(
      `Got HTTP ${res.status} fetching ${url}. This is almost certainly ` +
      `Vercel's Deployment Protection blocking the function from reading its ` +
      `own /embeddings.bin static asset. Two fixes (pick one):\n` +
      `  (A) Vercel → Project Settings → Deployment Protection → set to ` +
      `"Only Production Deployments" (or "Disabled" if this project ` +
      `doesn't need preview-link auth). Easiest fix.\n` +
      `  (B) Vercel → Project Settings → Deployment Protection → ` +
      `"Protection Bypass for Automation" → enable, copy the generated ` +
      `secret, and add it to Environment Variables as ` +
      `VERCEL_AUTOMATION_BYPASS_SECRET. The retriever already reads that ` +
      `env var and forwards it as the x-vercel-protection-bypass header.`
    );
  }

  if (!res.ok) {
    throw new Error(
      `Failed to fetch embeddings.bin from ${url} (status ${res.status}). ` +
      `Make sure web/public/embeddings.bin is committed to git and was ` +
      `regenerated by web/scripts/export-index.py against the latest index.`
    );
  }

  const buf = Buffer.from(await res.arrayBuffer());
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
}

export async function ensureLoaded(): Promise<void> {
  if (_chunks && _embeddings && _bm25) return;
  if (_loadPromise) return _loadPromise;

  _loadPromise = (async () => {
    const chunks = chunksData as Chunk[];
    const embeddings = await fetchEmbeddings();

    if (embeddings.length !== chunks.length * EMBEDDING_DIM) {
      throw new Error(
        `Embedding/chunk size mismatch: got ${embeddings.length} floats for ` +
        `${chunks.length} chunks at ${EMBEDDING_DIM} dims. ` +
        `Re-run web/scripts/export-index.py.`
      );
    }

    _chunks = chunks;
    _embeddings = embeddings;
    _bm25 = buildBM25(chunks.map(c => tokenize(c.text)));
  })();

  try {
    await _loadPromise;
  } catch (e) {
    _loadPromise = null; // allow retry on next request
    throw e;
  }
}

export async function getChunkCount(): Promise<number> {
  await ensureLoaded();
  return _chunks!.length;
}

export async function getCorpusStats() {
  await ensureLoaded();
  const byDocType: Record<string, number> = {};
  for (const c of _chunks!) {
    byDocType[c.doc_type] = (byDocType[c.doc_type] ?? 0) + 1;
  }
  return { total_chunks: _chunks!.length, by_doc_type: byDocType };
}

// Cosine similarity over L2-normalised vectors == dot product. The export
// script normalises the rows so we don't redo it here. We only need to
// L2-normalise the query vector before comparing.
function l2Normalise(v: Float32Array): void {
  let s = 0;
  for (let i = 0; i < v.length; i++) s += v[i] * v[i];
  s = Math.sqrt(s) || 1;
  for (let i = 0; i < v.length; i++) v[i] /= s;
}

function dotProduct(a: Float32Array, b: Float32Array, bOffset: number): number {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += a[i] * b[bOffset + i];
  return s;
}

function denseTopK(query: Float32Array, k: number): number[] {
  // Caller (retrieve) has already awaited ensureLoaded; we can read the
  // module-scope arrays synchronously here.
  const N = _chunks!.length;
  const scores = new Float32Array(N);
  for (let i = 0; i < N; i++) {
    scores[i] = dotProduct(query, _embeddings!, i * EMBEDDING_DIM);
  }
  const idx = Array.from({ length: N }, (_, i) => i);
  idx.sort((a, b) => scores[b] - scores[a]);
  return idx.slice(0, k);
}

export interface RetrieveOptions {
  topK?: number;
  docTypeFilter?: DocType[] | null;
}

/**
 * Hybrid dense + BM25 retrieval with HyDE-blended query embedding and
 * Reciprocal Rank Fusion. Mirrors RAGEngine.retrieve in rag.py.
 *
 * @param query  The user's natural-language question.
 * @param queryEmbedding  L2-normalisable embedding of `query` blended with the
 *                        HyDE doc (averaged; caller is responsible for the blend).
 */
export async function retrieve(
  query: string,
  queryEmbedding: Float32Array,
  opts: RetrieveOptions = {}
): Promise<SourceRef[]> {
  await ensureLoaded();
  const { topK = TOP_K, docTypeFilter = null } = opts;
  const fetchK = Math.min(RERANK_CANDIDATES, _chunks!.length);

  // Dense
  const q = new Float32Array(queryEmbedding);
  l2Normalise(q);
  const denseIdx = denseTopK(q, fetchK);
  const denseRank = new Map<number, number>();
  denseIdx.forEach((idx, rank) => denseRank.set(idx, rank));

  // BM25
  const bm25Idx = _bm25!.topK(tokenize(query), fetchK);
  const bm25Rank = new Map<number, number>();
  bm25Idx.forEach((idx, rank) => bm25Rank.set(idx, rank));

  // Reciprocal Rank Fusion
  const allIdx = new Set<number>([...denseRank.keys(), ...bm25Rank.keys()]);
  const rrfScores = new Map<number, number>();
  for (const idx of allIdx) {
    const dr = denseRank.get(idx);
    const br = bm25Rank.get(idx);
    const score =
      (dr !== undefined ? 1 / (RRF_K + dr) : 0) +
      (br !== undefined ? 1 / (RRF_K + br) : 0);
    rrfScores.set(idx, score);
  }
  const ranked = Array.from(rrfScores.entries()).sort((a, b) => b[1] - a[1]);

  const out: SourceRef[] = [];
  for (const [idx, rrfScore] of ranked) {
    const c = _chunks![idx];
    if (docTypeFilter && !docTypeFilter.includes(c.doc_type)) continue;
    out.push({
      num: out.length + 1,
      doc_type: c.doc_type,
      company: c.company,
      source: c.source,
      date: c.date,
      year: c.year,
      page: c.page,
      excerpt: c.text.slice(0, 300) + (c.text.length > 300 ? "…" : ""),
      score: Number(rrfScore.toFixed(4)),
    });
    if (out.length >= topK) break;
  }
  return out;
}

// Returns the full text body of a chunk by 1-indexed source number — used to
// build the user-prompt context with the original (untruncated) passages.
// Synchronous because the caller has already awaited ensureLoaded() via
// retrieve(); the chunks array is in module memory at this point.
export function getChunkText(sourceNum: number, sources: SourceRef[]): string {
  const ref = sources[sourceNum - 1];
  if (!ref) return "";
  // Find the chunk whose source/date/page match the SourceRef. (The retrieval
  // path builds SourceRefs from the same array, so a structural lookup is OK.)
  for (const c of _chunks!) {
    if (
      c.source === ref.source &&
      c.date === ref.date &&
      c.page === ref.page &&
      c.text.startsWith(ref.excerpt.slice(0, 50))
    ) {
      return c.text;
    }
  }
  return ref.excerpt;
}
